Cours_Get_Post_Formulaires/Models/Etudiant.cs
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;

namespace Cours_Get_Post_Formulaires.Models
{
    public class Etudiant
    {
        [Display(Name = "Numéro", Prompt = "Entrez votre numéro ici")]
        public int Numero { get; set; }

        [Display(Name = "Nom", Prompt = "Entrez votre nom ici")]
        public string Nom { get; set; }

        [Display(Name = "Prénom", Prompt = "Entrez votre prénom ici")]
        public string Prenom { get; set; }

        [Display(Name = "Date de naissance", Prompt = "Entrez votre date de naissance ici")]
        public DateTime DateNaissance { get; set; }

        [Display(Name = "Tél.", Prompt = "Entrez votre numéro de téléphone ici")]
        public string Telephone { get; set; }
    }
}

Cours_Get_Post_Formulaires/Controllers/RequetesController.cs
using Cours_Get_Post_Formulaires.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text;

namespace Cours_Get_Post_Formulaires.Controllers
{
    public class RequetesController : Controller
    {
        [HttpGet]
        public ViewResult ReceptionRequeteGet(string nom)
        {
            ViewBag.Nom = nom;
            ViewBag.Prenom = this.Request.Query["prenom"];

            return View();
        }

        /// <summary>
        /// Méthode d'action qui affiche la page 
        /// dans laquelle il y a un lien.
        /// </summary>
        /// <returns>retourne la vue AfficherLien</returns>
        [HttpGet]
        public ViewResult AfficherLien()
        {
            return View();
        }

        /// <summary>
        /// Méthode d'action qui affiche un paragraphe qui donne 
        /// des détails sur le chemin et la valeur du paramètre envoyé dans l'URL.
        /// </summary>
        /// <param name="param">Un paramètre</param>
        /// <returns>Retourne une chaîne de caractères de type ContentResult</returns>
        [HttpGet]
        public ContentResult Lien(int param)
        {
            return Content("<p> Vous avez cliqué sur le lien qui mène vers <b>" + this.Request.Path +
                "</b> avec le paramètre <b>" + param + " </b></p>",
                "text/html", Encoding.UTF8);
        }

        [HttpGet]
        public ActionResult Saisie()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Saisie(Etudiant etudiant)
        {
            return View("Affichage", etudiant);
        }


        [HttpPost]
        public ActionResult Saisie(string numero, string nom, string prenom, string dateNaissance, string telephone)
        {
            Etudiant etudiant = new Etudiant();
            etudiant.Numero = Convert.ToInt32(numero);
            etudiant.Nom = nom;
            etudiant.Prenom = prenom;
            etudiant.DateNaissance = DateTime.Parse(dateNaissance);
            etudiant.Telephone = telephone;

            return View("Affichage", etudiant);
        }

        [HttpPost]
        public ActionResult Saisie()
        {
            Etudiant etudiant = new Etudiant();
            etudiant.Numero = Convert.ToInt32(this.Request.Form["Numero"].ElementAt(0));
            etudiant.Nom = this.Request.Form["Nom"].ElementAt(0);
            etudiant.Prenom = this.Request.Form["Prenom"].ElementAt(0);
            etudiant.DateNaissance = DateTime.Parse(this.Request.Form["DateNaissance"].ElementAt(0));
            etudiant.Telephone = this.Request.Form["Telephone"].ElementAt(0);

            return View("Affichage", etudiant);
        }
    }
}

Cours_Get_Post_Formulaires/Views/Requetes/Affichage.cshtml
@model Cours_Get_Post_Formulaires.Models.Etudiant

@{
    ViewBag.Titre = "Affichage";
}
﻿
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Titre"]</title>
</head>
<body>
    <h2>Les données envoyées sont:</h2>
    <ul>
        <li><label asp-for="Numero"></label>: @Model.Numero</li>
        <li><label asp-for="Nom"></label>: @Model.Nom</li>
        <li><label asp-for="Prenom"></label>: @Model.Prenom</li>
        <li><label asp-for="DateNaissance"></label>: @Model.DateNaissance</li>
        <li><label asp-for="Telephone"></label>: @Model.Telephone</li>
    </ul>
</body>

</html>

Cours_Get_Post_Formulaires/Views/Requetes/AfficherLien.cshtml
@{
    ViewBag.Titre = "Page qui affiche un lien à cliquer pour montrer le paramètre envoyé à la méthode d'action Lien en HTTP Get";
    ViewBag.id = 50;
}
﻿
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Titre"]</title>
</head>
<body>
    <h1>@ViewData["Titre"]</h1>

    <a asp-controller="Requetes" asp-action="Lien" asp-route-param="@ViewBag.id">
        Cliquez sur ce lien pour voir les pramaètres envoyés à la méthode d'action Lien.
    </a>
</body>

</html>

Cours_Get_Post_Formulaires/Views/Requetes/ReceptionRequeteGet.cshtml
@{
    ViewBag.Titre = "Page retournée après l'appel à la méthode d'action ReceptionRequeteGet via une requête HTTP Get";
}
﻿
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Titre"]</title>
</head>
<body>
    <h1>@ViewData["Titre"]</h1>

    <h2>voici les paramètres envoyés sur l'url</h2>

    <h4>Nom:@ViewBag.Nom</h4>
    <h4>Prenom: @ViewBag.Prenom</h4>
</body>

</html>

Cours_Get_Post_Formulaires/Views/Requetes/Saisie.cshtml
@model Cours_Get_Post_Formulaires.Models.Etudiant

@{
    ViewBag.Titre = "Saisie";
}
﻿
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Titre"]</title>
</head>
<body>
    <form asp-controller="Requetes" asp-action="Saisie" method="post">
        <div>
            <label asp-for="Numero"></label>
            <input asp-for="Numero" />
        </div>
        <div>
            <label asp-for="Nom"></label>
            <input asp-for="Nom" />
        </div>
        <div>
            <label asp-for="Prenom"></label>
            <input asp-for="Prenom" />
        </div>
        <div>
            <label asp-for="DateNaissance"></label>
            <input asp-for="DateNaissance" />
        </div>
        <div>
            <label asp-for="Telephone"></label>
            <input asp-for="Telephone" />
        </div>
        <div>
            <input type="submit" value="Envoyer" />
        </div>

    </form >
</body>

</html>